from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
OUTPUT_DIR = BASE_DIR / "output"
CHART_DIR = OUTPUT_DIR / "charts"
EXPORT_DIR = OUTPUT_DIR / "exports"
DB_PATH = DATA_DIR / "population_insight.db"
FLASK_SECRET_KEY = "population-insight-course-design"
WEB_PAGE_SIZE = 10

YEAR_MIN = 2000
YEAR_MAX = 2035

DEFAULT_USERS = [
    {"username": "admin", "password": "admin123", "role": "admin"},
    {"username": "viewer", "password": "viewer123", "role": "viewer"},
]

ALLOWED_SORT_FIELDS = {
    "id": "id",
    "region": "region",
    "year": "year",
    "total_population": "total_population",
    "birth_rate": "birth_rate",
    "death_rate": "death_rate",
    "natural_growth_rate": "natural_growth_rate",
    "aging_rate": "aging_rate",
    "urbanization_rate": "urbanization_rate",
}

METRIC_LABELS = {
    "total_population": "总人口",
    "male_population": "男性人口",
    "female_population": "女性人口",
    "birth_rate": "出生率",
    "death_rate": "死亡率",
    "natural_growth_rate": "自然增长率",
    "aging_rate": "老龄化率",
    "urbanization_rate": "城镇化率",
}

def _to_people(ten_thousand_people: float) -> int:
    return int(round(ten_thousand_people * 10000))


def _record(
    *,
    region: str,
    year: int,
    total_population_10k: float,
    male_population_10k: float,
    female_population_10k: float,
    birth_rate: float,
    death_rate: float,
    natural_growth_rate: float,
    aging_rate: float,
    urbanization_rate: float,
    remarks: str,
    aging_rate_basis: str = "60_plus",
    data_source_name: str = "",
    source_url: str = "",
    data_quality: str = "",
) -> dict:
    return {
        "region": region,
        "year": year,
        "total_population": _to_people(total_population_10k),
        "male_population": _to_people(male_population_10k),
        "female_population": _to_people(female_population_10k),
        "birth_rate": round(birth_rate, 2),
        "death_rate": round(death_rate, 2),
        "natural_growth_rate": round(natural_growth_rate, 2),
        "aging_rate": round(aging_rate, 2),
        "urbanization_rate": round(urbanization_rate, 2),
        "remarks": remarks,
        "aging_rate_basis": aging_rate_basis,
        "data_source_name": data_source_name,
        "source_url": source_url,
        "data_quality": data_quality,
    }


def _official_2024_record(
    region: str,
    total_population_10k: float,
    male_sample: int,
    female_sample: int,
    birth_rate: float,
    death_rate: float,
    natural_growth_rate: float,
    aging_65_sample: int,
    urbanization_rate: float,
) -> dict:
    total_population = _to_people(total_population_10k)
    sample_total = male_sample + female_sample
    male_population = int(round(total_population * male_sample / sample_total))
    female_population = total_population - male_population
    aging_rate = aging_65_sample / sample_total * 100 if sample_total else 0
    return {
        "region": region,
        "year": 2024,
        "total_population": total_population,
        "male_population": male_population,
        "female_population": female_population,
        "birth_rate": round(birth_rate, 2),
        "death_rate": round(death_rate, 2),
        "natural_growth_rate": round(natural_growth_rate, 2),
        "aging_rate": round(aging_rate, 2),
        "urbanization_rate": round(urbanization_rate, 2),
        "remarks": "依据《中国统计年鉴2025》人口章节2-7、2-9、2-11整理；男女人口按2-9样本性别结构折算，老龄化率按65岁及以上人口占比。",
        "aging_rate_basis": "65_plus",
        "data_source_name": "中国统计年鉴2025人口章节",
        "source_url": "https://www.stats.gov.cn/sj/ndsj/2025/indexch.htm",
        "data_quality": "official_sample_derived",
    }


INITIAL_POPULATION_RECORDS = [
    _record(
        region="北京市",
        year=2015,
        total_population_10k=2188.3,
        male_population_10k=1126.2,
        female_population_10k=1062.1,
        birth_rate=7.89,
        death_rate=4.91,
        natural_growth_rate=2.98,
        aging_rate=16.73,
        urbanization_rate=86.71,
        remarks="依据北京统计年鉴2021整理，老龄化率按60岁及以上常住人口占比。",
    ),
    _record(
        region="北京市",
        year=2016,
        total_population_10k=2195.4,
        male_population_10k=1126.1,
        female_population_10k=1069.3,
        birth_rate=9.23,
        death_rate=5.16,
        natural_growth_rate=4.07,
        aging_rate=17.25,
        urbanization_rate=86.76,
        remarks="依据北京统计年鉴2021整理，老龄化率按60岁及以上常住人口占比。",
    ),
    _record(
        region="北京市",
        year=2017,
        total_population_10k=2194.4,
        male_population_10k=1123.9,
        female_population_10k=1070.5,
        birth_rate=8.97,
        death_rate=5.24,
        natural_growth_rate=3.73,
        aging_rate=17.98,
        urbanization_rate=86.93,
        remarks="依据北京统计年鉴2021整理，老龄化率按60岁及以上常住人口占比。",
    ),
    _record(
        region="北京市",
        year=2018,
        total_population_10k=2191.7,
        male_population_10k=1122.2,
        female_population_10k=1069.5,
        birth_rate=8.13,
        death_rate=5.50,
        natural_growth_rate=2.63,
        aging_rate=18.60,
        urbanization_rate=87.09,
        remarks="依据北京统计年鉴2021整理，老龄化率按60岁及以上常住人口占比。",
    ),
    _record(
        region="北京市",
        year=2019,
        total_population_10k=2190.1,
        male_population_10k=1120.5,
        female_population_10k=1069.6,
        birth_rate=7.98,
        death_rate=5.40,
        natural_growth_rate=2.58,
        aging_rate=19.10,
        urbanization_rate=87.35,
        remarks="依据北京统计年鉴2021整理，老龄化率按60岁及以上常住人口占比。",
    ),
    _record(
        region="北京市",
        year=2020,
        total_population_10k=2189.0,
        male_population_10k=1119.4,
        female_population_10k=1069.6,
        birth_rate=6.98,
        death_rate=4.59,
        natural_growth_rate=2.39,
        aging_rate=19.64,
        urbanization_rate=87.55,
        remarks="依据北京统计年鉴2021整理，老龄化率按60岁及以上常住人口占比。",
    ),
    _record(
        region="北京市",
        year=2021,
        total_population_10k=2188.6,
        male_population_10k=1117.7,
        female_population_10k=1070.9,
        birth_rate=6.35,
        death_rate=5.39,
        natural_growth_rate=0.96,
        aging_rate=20.18,
        urbanization_rate=87.55,
        remarks="依据北京统计公报2021整理，老龄化率按60岁及以上常住人口占比。",
    ),
    _record(
        region="北京市",
        year=2022,
        total_population_10k=2184.3,
        male_population_10k=1117.0,
        female_population_10k=1067.3,
        birth_rate=5.67,
        death_rate=5.72,
        natural_growth_rate=-0.05,
        aging_rate=21.29,
        urbanization_rate=87.60,
        remarks="依据北京市2022年统计公报及公开人口统计整理，性别人数按公开占比折算，老龄化率按60岁及以上常住人口占比。",
    ),
    _record(
        region="北京市",
        year=2023,
        total_population_10k=2185.8,
        male_population_10k=1113.3,
        female_population_10k=1072.5,
        birth_rate=5.63,
        death_rate=6.13,
        natural_growth_rate=-0.50,
        aging_rate=22.64,
        urbanization_rate=87.80,
        remarks="依据2023年统计公报及中国统计年鉴2024整理，老龄化率按60岁及以上常住人口占比。",
    ),
    _record(
        region="北京市",
        year=2024,
        total_population_10k=2183.2,
        male_population_10k=1111.3,
        female_population_10k=1071.9,
        birth_rate=6.09,
        death_rate=6.08,
        natural_growth_rate=0.01,
        aging_rate=23.54,
        urbanization_rate=88.20,
        remarks="依据统计公报2024整理，老龄化率按60岁及以上常住人口占比。",
    ),
    _record(
        region="广东省",
        year=2020,
        total_population_10k=12624.0,
        male_population_10k=6699.56,
        female_population_10k=5924.44,
        birth_rate=10.28,
        death_rate=4.70,
        natural_growth_rate=5.58,
        aging_rate=12.35,
        urbanization_rate=74.15,
        remarks="依据广东统计年鉴2022及第七次全国人口普查公报整理，老龄化率按60岁及以上常住人口占比。",
    ),
    _record(
        region="广东省",
        year=2021,
        total_population_10k=12684.0,
        male_population_10k=6693.0,
        female_population_10k=5991.0,
        birth_rate=9.35,
        death_rate=4.83,
        natural_growth_rate=4.52,
        aging_rate=12.73,
        urbanization_rate=74.63,
        remarks="依据2021年广东统计公报及人口结构分析整理，老龄化率按60岁及以上常住人口占比。",
    ),
    _record(
        region="广东省",
        year=2022,
        total_population_10k=12656.8,
        male_population_10k=6673.8,
        female_population_10k=5983.0,
        birth_rate=8.30,
        death_rate=4.97,
        natural_growth_rate=3.33,
        aging_rate=13.45,
        urbanization_rate=74.79,
        remarks="依据2022年广东省国民经济和社会发展统计公报整理，老龄化率按60岁及以上常住人口占比。",
    ),
    _record(
        region="广东省",
        year=2023,
        total_population_10k=12706.0,
        male_population_10k=6689.0,
        female_population_10k=6017.0,
        birth_rate=8.12,
        death_rate=5.36,
        natural_growth_rate=2.76,
        aging_rate=14.24,
        urbanization_rate=75.42,
        remarks="依据2023年统计公报、中国统计年鉴2024及老龄人口公开报道整理，老龄化率按60岁及以上常住人口占比。",
    ),
    _record(
        region="广东省",
        year=2024,
        total_population_10k=12780.0,
        male_population_10k=6728.0,
        female_population_10k=6052.0,
        birth_rate=8.89,
        death_rate=5.20,
        natural_growth_rate=3.69,
        aging_rate=14.86,
        urbanization_rate=75.91,
        remarks="依据2024年广东省国民经济和社会发展统计公报整理，老龄化率按60岁及以上常住人口占比。",
    ),
]

INITIAL_POPULATION_RECORDS.extend(
    [
        _official_2024_record("北京市", 2183, 11437, 11033, 6.09, 6.08, 0.01, 3703, 88.22),
        _official_2024_record("天津市", 1364, 7172, 6865, 4.99, 6.96, -1.97, 2606, 86.01),
        _official_2024_record("河北省", 7378, 37696, 38248, 5.90, 8.22, -2.32, 12498, 63.42),
        _official_2024_record("山西省", 3446, 18077, 17387, 6.94, 8.33, -1.39, 5598, 66.32),
        _official_2024_record("内蒙古自治区", 2388, 12565, 12013, 5.52, 8.36, -2.84, 3942, 70.73),
        _official_2024_record("辽宁省", 4155, 21020, 21743, 4.32, 9.62, -5.30, 9366, 74.18),
        _official_2024_record("吉林省", 2317, 11875, 11969, 4.17, 9.02, -4.85, 4629, 65.78),
        _official_2024_record("黑龙江省", 3029, 15549, 15625, 3.35, 9.69, -6.34, 6051, 68.05),
        _official_2024_record("上海市", 2480, 13206, 12314, 4.75, 6.28, -1.53, 5169, 89.85),
        _official_2024_record("江苏省", 8526, 44476, 43280, 4.98, 7.48, -2.50, 16478, 75.53),
        _official_2024_record("浙江省", 6670, 35828, 32823, 6.17, 6.53, -0.36, 10789, 75.46),
        _official_2024_record("安徽省", 6123, 32161, 30859, 6.17, 8.41, -2.24, 9885, 62.57),
        _official_2024_record("福建省", 4193, 22321, 20841, 6.95, 6.71, 0.24, 5591, 71.80),
        _official_2024_record("江西省", 4502, 23925, 22414, 6.65, 7.23, -0.58, 6435, 63.77),
        _official_2024_record("山东省", 10080, 52391, 51361, 6.42, 8.09, -1.67, 18400, 66.48),
        _official_2024_record("河南省", 9785, 50450, 50266, 7.78, 7.89, -0.11, 15144, 59.22),
        _official_2024_record("湖北省", 5834, 30725, 29323, 5.38, 8.52, -3.14, 10385, 66.35),
        _official_2024_record("湖南省", 6539, 34434, 32869, 5.89, 8.93, -3.04, 11228, 62.07),
        _official_2024_record("广东省", 12780, 69252, 62290, 8.89, 5.20, 3.69, 13399, 75.91),
        _official_2024_record("广西壮族自治区", 5013, 26652, 24942, 8.37, 7.49, 0.88, 7208, 57.39),
        _official_2024_record("海南省", 1048, 5725, 5060, 9.37, 6.31, 3.06, 1278, 63.08),
        _official_2024_record("重庆市", 3190, 16520, 16308, 5.99, 8.87, -2.88, 6194, 72.14),
        _official_2024_record("四川省", 8364, 43367, 42724, 6.41, 9.43, -3.02, 15878, 60.10),
        _official_2024_record("贵州省", 3860, 20310, 19422, 10.74, 7.74, 3.00, 5127, 56.65),
        _official_2024_record("云南省", 4655, 24599, 23319, 8.62, 8.45, 0.17, 5783, 54.11),
        _official_2024_record("西藏自治区", 370, 2007, 1806, 13.87, 5.44, 8.43, 240, 39.68),
        _official_2024_record("陕西省", 3953, 20742, 19950, 7.36, 8.05, -0.69, 6381, 66.14),
        _official_2024_record("甘肃省", 2458, 12832, 12468, 8.00, 8.90, -0.90, 3449, 56.83),
        _official_2024_record("青海省", 593, 3068, 3041, 10.11, 7.41, 2.70, 646, 63.86),
        _official_2024_record("宁夏回族自治区", 729, 3808, 3691, 10.97, 6.45, 4.52, 798, 68.22),
        _official_2024_record("新疆维吾尔自治区", 2623, 13963, 13032, 9.42, 6.05, 3.37, 2393, 60.36),
    ]
)

INITIAL_REGIONS = [
    {
        "name": "北京市",
        "region_type": "直辖市",
        "admin_code": "110000",
        "parent_region": "中国",
        "remarks": "国家中心城市，人口结构变化具有代表性。",
    },
    {
        "name": "广东省",
        "region_type": "省",
        "admin_code": "440000",
        "parent_region": "中国",
        "remarks": "常住人口规模长期位居全国前列。",
    },
    {
        "name": "山东省",
        "region_type": "省",
        "admin_code": "370000",
        "parent_region": "中国",
        "remarks": "沿海人口大省，适合用于省际人口结构对比。",
    },
    {
        "name": "江苏省",
        "region_type": "省",
        "admin_code": "320000",
        "parent_region": "中国",
        "remarks": "长三角地区人口与城镇化分析重点省份。",
    },
    {
        "name": "上海市",
        "region_type": "直辖市",
        "admin_code": "310000",
        "parent_region": "中国",
        "remarks": "超大城市人口结构和老龄化分析重点地区。",
    },
    {
        "name": "天津市",
        "region_type": "直辖市",
        "admin_code": "120000",
        "parent_region": "中国",
        "remarks": "环渤海地区直辖市，适合与北京、河北进行人口流动和城镇化对比。",
    },
    {
        "name": "河北省",
        "region_type": "省",
        "admin_code": "130000",
        "parent_region": "中国",
        "remarks": "京津冀人口协同发展分析重点省份。",
    },
    {
        "name": "山西省",
        "region_type": "省",
        "admin_code": "140000",
        "parent_region": "中国",
        "remarks": "中部地区资源型省份，适合观察人口转型趋势。",
    },
    {
        "name": "内蒙古自治区",
        "region_type": "自治区",
        "admin_code": "150000",
        "parent_region": "中国",
        "remarks": "北方边疆自治区，适合人口密度和城镇化对比。",
    },
    {
        "name": "辽宁省",
        "region_type": "省",
        "admin_code": "210000",
        "parent_region": "中国",
        "remarks": "东北地区人口结构变化重点省份。",
    },
    {
        "name": "吉林省",
        "region_type": "省",
        "admin_code": "220000",
        "parent_region": "中国",
        "remarks": "东北地区人口自然增长和流动分析样本。",
    },
    {
        "name": "黑龙江省",
        "region_type": "省",
        "admin_code": "230000",
        "parent_region": "中国",
        "remarks": "东北边疆省份，适合人口减少和老龄化趋势研究。",
    },
    {
        "name": "浙江省",
        "region_type": "省",
        "admin_code": "330000",
        "parent_region": "中国",
        "remarks": "长三角人口流入和城镇化分析重点省份。",
    },
    {
        "name": "安徽省",
        "region_type": "省",
        "admin_code": "340000",
        "parent_region": "中国",
        "remarks": "长三角一体化人口变化分析省份。",
    },
    {
        "name": "福建省",
        "region_type": "省",
        "admin_code": "350000",
        "parent_region": "中国",
        "remarks": "东南沿海人口结构与城镇化分析省份。",
    },
    {
        "name": "江西省",
        "region_type": "省",
        "admin_code": "360000",
        "parent_region": "中国",
        "remarks": "中部地区人口结构变化分析省份。",
    },
    {
        "name": "河南省",
        "region_type": "省",
        "admin_code": "410000",
        "parent_region": "中国",
        "remarks": "人口大省，适合与山东、广东、四川等地区横向对比。",
    },
    {
        "name": "湖北省",
        "region_type": "省",
        "admin_code": "420000",
        "parent_region": "中国",
        "remarks": "中部地区人口与城镇化分析重点省份。",
    },
    {
        "name": "湖南省",
        "region_type": "省",
        "admin_code": "430000",
        "parent_region": "中国",
        "remarks": "中部地区人口年龄结构分析省份。",
    },
    {
        "name": "广西壮族自治区",
        "region_type": "自治区",
        "admin_code": "450000",
        "parent_region": "中国",
        "remarks": "西南沿海自治区，适合人口结构和民族地区发展对比。",
    },
    {
        "name": "海南省",
        "region_type": "省",
        "admin_code": "460000",
        "parent_region": "中国",
        "remarks": "热带岛屿省份，适合人口流入和城镇化分析。",
    },
    {
        "name": "重庆市",
        "region_type": "直辖市",
        "admin_code": "500000",
        "parent_region": "中国",
        "remarks": "西部直辖市，适合城乡人口结构分析。",
    },
    {
        "name": "四川省",
        "region_type": "省",
        "admin_code": "510000",
        "parent_region": "中国",
        "remarks": "西部人口大省，适合区域人口规模和老龄化对比。",
    },
    {
        "name": "贵州省",
        "region_type": "省",
        "admin_code": "520000",
        "parent_region": "中国",
        "remarks": "西南地区人口和城镇化变化分析省份。",
    },
    {
        "name": "云南省",
        "region_type": "省",
        "admin_code": "530000",
        "parent_region": "中国",
        "remarks": "西南边疆省份，适合人口结构和民族地区发展对比。",
    },
    {
        "name": "西藏自治区",
        "region_type": "自治区",
        "admin_code": "540000",
        "parent_region": "中国",
        "remarks": "西南边疆自治区，适合人口密度和城镇化对比。",
    },
    {
        "name": "陕西省",
        "region_type": "省",
        "admin_code": "610000",
        "parent_region": "中国",
        "remarks": "西北地区人口与城镇化分析重点省份。",
    },
    {
        "name": "甘肃省",
        "region_type": "省",
        "admin_code": "620000",
        "parent_region": "中国",
        "remarks": "西北地区人口结构变化分析省份。",
    },
    {
        "name": "青海省",
        "region_type": "省",
        "admin_code": "630000",
        "parent_region": "中国",
        "remarks": "西北高原省份，适合人口密度和民族地区发展对比。",
    },
    {
        "name": "宁夏回族自治区",
        "region_type": "自治区",
        "admin_code": "640000",
        "parent_region": "中国",
        "remarks": "西北自治区，适合人口规模和结构变化分析。",
    },
    {
        "name": "新疆维吾尔自治区",
        "region_type": "自治区",
        "admin_code": "650000",
        "parent_region": "中国",
        "remarks": "西北边疆自治区，适合人口规模、结构和城镇化对比。",
    },
]

INITIAL_DATA_SOURCES = [
    {
        "name": "北京市人口统计",
        "publisher": "北京市人民政府",
        "source_url": "https://www.beijing.gov.cn/renwen/bjgk/rk/rktj/",
        "published_date": "2025-03-01",
        "reliability_level": "高",
        "remarks": "用于北京市人口年度数据核验。",
    },
    {
        "name": "广东省统计公报",
        "publisher": "广东省统计局",
        "source_url": "https://stats.gd.gov.cn/",
        "published_date": "2025-03-01",
        "reliability_level": "高",
        "remarks": "用于广东省人口年度数据核验。",
    },
    {
        "name": "山东省统计公报",
        "publisher": "山东省统计局",
        "source_url": "https://tjj.shandong.gov.cn/art/2025/3/5/art_6196_10316729.html",
        "published_date": "2025-03-05",
        "reliability_level": "高",
        "remarks": "用于山东省人口年度数据采集和核验。",
    },
    {
        "name": "江苏省统计公报",
        "publisher": "江苏省统计局",
        "source_url": "https://tj.jiangsu.gov.cn/art/2025/3/15/art_85764_11514117.html",
        "published_date": "2025-03-15",
        "reliability_level": "高",
        "remarks": "用于江苏省人口年度数据采集和核验。",
    },
    {
        "name": "上海市统计公报",
        "publisher": "上海市统计局",
        "source_url": "https://tjj.sh.gov.cn/tjgb/20250324/a7fe18c6d5c24d66bfca89c5bb4cdcfb.html",
        "published_date": "2025-03-25",
        "reliability_level": "高",
        "remarks": "用于上海市人口年度数据采集和核验。",
    },
    {
        "name": "天津市统计局",
        "publisher": "天津市统计局",
        "source_url": "https://stats.tj.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于天津市人口统计数据采集和核验。",
    },
    {
        "name": "河北省统计局",
        "publisher": "河北省统计局",
        "source_url": "https://tjj.hebei.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于河北省人口统计数据采集和核验。",
    },
    {
        "name": "山西省统计局",
        "publisher": "山西省统计局",
        "source_url": "https://tjj.shanxi.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于山西省人口统计数据采集和核验。",
    },
    {
        "name": "内蒙古自治区统计局",
        "publisher": "内蒙古自治区统计局",
        "source_url": "https://tj.nmg.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于内蒙古自治区人口统计数据采集和核验。",
    },
    {
        "name": "辽宁省统计局",
        "publisher": "辽宁省统计局",
        "source_url": "https://tjj.ln.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于辽宁省人口统计数据采集和核验。",
    },
    {
        "name": "吉林省统计局",
        "publisher": "吉林省统计局",
        "source_url": "https://tjj.jl.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于吉林省人口统计数据采集和核验。",
    },
    {
        "name": "黑龙江省统计局",
        "publisher": "黑龙江省统计局",
        "source_url": "https://tjj.hlj.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于黑龙江省人口统计数据采集和核验。",
    },
    {
        "name": "浙江省统计局",
        "publisher": "浙江省统计局",
        "source_url": "https://tjj.zj.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于浙江省人口统计数据采集和核验。",
    },
    {
        "name": "安徽省统计局",
        "publisher": "安徽省统计局",
        "source_url": "https://tjj.ah.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于安徽省人口统计数据采集和核验。",
    },
    {
        "name": "福建省统计局",
        "publisher": "福建省统计局",
        "source_url": "https://tjj.fujian.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于福建省人口统计数据采集和核验。",
    },
    {
        "name": "江西省统计局",
        "publisher": "江西省统计局",
        "source_url": "https://tjj.jiangxi.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于江西省人口统计数据采集和核验。",
    },
    {
        "name": "河南省统计局",
        "publisher": "河南省统计局",
        "source_url": "https://tjj.henan.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于河南省人口统计数据采集和核验。",
    },
    {
        "name": "湖北省统计局",
        "publisher": "湖北省统计局",
        "source_url": "https://tjj.hubei.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于湖北省人口统计数据采集和核验。",
    },
    {
        "name": "湖南省统计局",
        "publisher": "湖南省统计局",
        "source_url": "https://tjj.hunan.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于湖南省人口统计数据采集和核验。",
    },
    {
        "name": "广西壮族自治区统计局",
        "publisher": "广西壮族自治区统计局",
        "source_url": "https://tjj.gxzf.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于广西壮族自治区人口统计数据采集和核验。",
    },
    {
        "name": "海南省统计局",
        "publisher": "海南省统计局",
        "source_url": "https://stats.hainan.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于海南省人口统计数据采集和核验。",
    },
    {
        "name": "重庆市统计局",
        "publisher": "重庆市统计局",
        "source_url": "https://tjj.cq.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于重庆市人口统计数据采集和核验。",
    },
    {
        "name": "四川省统计局",
        "publisher": "四川省统计局",
        "source_url": "https://tjj.sc.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于四川省人口统计数据采集和核验。",
    },
    {
        "name": "贵州省统计局",
        "publisher": "贵州省统计局",
        "source_url": "https://stjj.guizhou.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于贵州省人口统计数据采集和核验。",
    },
    {
        "name": "云南省统计局",
        "publisher": "云南省统计局",
        "source_url": "https://stats.yn.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于云南省人口统计数据采集和核验。",
    },
    {
        "name": "西藏自治区统计局",
        "publisher": "西藏自治区统计局",
        "source_url": "https://tjj.xizang.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于西藏自治区人口统计数据采集和核验。",
    },
    {
        "name": "陕西省统计局",
        "publisher": "陕西省统计局",
        "source_url": "https://tjj.shaanxi.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于陕西省人口统计数据采集和核验。",
    },
    {
        "name": "甘肃省统计局",
        "publisher": "甘肃省统计局",
        "source_url": "https://tjj.gansu.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于甘肃省人口统计数据采集和核验。",
    },
    {
        "name": "青海省统计局",
        "publisher": "青海省统计局",
        "source_url": "https://tjj.qinghai.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于青海省人口统计数据采集和核验。",
    },
    {
        "name": "宁夏回族自治区统计局",
        "publisher": "宁夏回族自治区统计局",
        "source_url": "https://tjj.nx.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于宁夏回族自治区人口统计数据采集和核验。",
    },
    {
        "name": "新疆维吾尔自治区统计局",
        "publisher": "新疆维吾尔自治区统计局",
        "source_url": "https://tjj.xinjiang.gov.cn/",
        "published_date": "",
        "reliability_level": "高",
        "remarks": "用于新疆维吾尔自治区人口统计数据采集和核验。",
    },
]

INITIAL_POPULATION_INDICATORS = [
    {
        "code": "child_ratio",
        "name": "少儿人口占比",
        "unit": "%",
        "description": "0-14岁人口占常住人口比重。",
    },
    {
        "code": "working_age_ratio",
        "name": "劳动年龄人口占比",
        "unit": "%",
        "description": "15-59岁人口占常住人口比重。",
    },
    {
        "code": "dependency_ratio",
        "name": "总抚养比",
        "unit": "%",
        "description": "少儿与老年人口对劳动年龄人口的比例。",
    },
]

INITIAL_ANNUAL_INDICATOR_VALUES = [
    {"region": "北京市", "year": 2024, "indicator_code": "child_ratio", "value": 11.2, "remarks": "样例扩展指标。"},
    {"region": "北京市", "year": 2024, "indicator_code": "working_age_ratio", "value": 65.3, "remarks": "样例扩展指标。"},
    {"region": "北京市", "year": 2024, "indicator_code": "dependency_ratio", "value": 53.1, "remarks": "样例扩展指标。"},
    {"region": "广东省", "year": 2024, "indicator_code": "child_ratio", "value": 18.6, "remarks": "样例扩展指标。"},
    {"region": "广东省", "year": 2024, "indicator_code": "working_age_ratio", "value": 66.5, "remarks": "样例扩展指标。"},
    {"region": "广东省", "year": 2024, "indicator_code": "dependency_ratio", "value": 50.4, "remarks": "样例扩展指标。"},
]
